export const ACTION_TYPES = {
  FETCH_PRODUCTS_LIST: 'FETCH_PRODUCTS_LIST',
  SET_PRODUCTS_LIST: 'SET_PRODUCTS_LIST'
};

export const fetchProductsList = () => ({
  type: ACTION_TYPES.FETCH_PRODUCTS_LIST
});
